---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'pure-theme'
---
Name: cwpcoreconfig
After: 'framework/*','cms/*'
---
Injector:
  RequestProcessor:
    properties:
      filters:
        - '%$CwpInitialisationFilter'
DBField:
  extensions:
   - RichLinksExtension
Controller:
  extensions:
   - CwpControllerExtension
Group:
  extensions:
   - CwpHtmlEditorConfig
HtmlEditorField_Toolbar:
  extensions:
   - CustomHtmlEditorFieldToolbar
GDBackend:
  default_quality: 90
LeftAndMain:
  extra_requirements_css:
   - 'cwp-core/css/custom.css'
Session:
  timeout: 3600
LeftAndMain:
  session_keepalive_ping: false
PasswordField:
  autocomplete: false
Security:
  login_recording: false
Member:
  lock_out_after_incorrect_logins: 5
  lock_out_delay_mins: 15
CwpInitialisationFilter:
  egress_proxy_default_enabled: true

